### ISSUE TITLE
Docker image not available?

### ISSUE THREAD

**Issue by drnic** [mastertinner/apache-directory-index-resource#4]
The badges on readme confirm what I'm seeing, the image isn't available for download. Ideas?

**Comment by drnic** [comment]
I've pushed a build of image to my own docker account for anyone else needing it:

```yaml
resource_types:
- name: apache-directory-index
  type: docker-image
  source:
    # manual build of image due to https://github.com/mastertinner/apache-directory-index-resource/issues/4
    repository: drnic/apache-directory-index-resource
    tag: 09dcf40f
    # repository: mastertinner/apache-directory-index-resource
    # tag: latest
```
